version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # root workspace
    schedule:
      interval: 'weekly'
    groups:
      all-yarn-dependencies:
        patterns:
          - '*'
      eslint-dependencies:
        patterns:
          - 'eslint*'
          - '@typescript-eslint*'
          - 'eslint-plugin*'
          - 'eslint-config*'
        update-types:
          - 'minor'
          - 'patch'
      typescript-dependencies:
        patterns:
          - 'typescript'
          - 'ts-*'
          - 'tsconfig*'
        update-types:
          - 'minor'
          - 'patch'
      node-types:
        patterns:
          - '@types/node'
        update-types:
          - 'minor'
          - 'patch'
      prettier-dependencies:
        patterns:
          - 'prettier*'
          - 'eslint-config-prettier'
          - 'eslint-plugin-prettier'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    groups:
      all-yarn-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/smart-contracts'
    schedule:
      interval: 'weekly'
    groups:
      hardhat-deps:
        patterns:
          - 'hardhat'
          - 'hardhat*'
          - '@nomicfoundation*'
      contracts:
        patterns:
          - '@openzeppelin/'
          - 'solmate'
      all-yarn-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/claimer'
    schedule:
      interval: 'weekly'
    groups:
      all-yarn-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/abis'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/addresses'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/client'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/helpers'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/packages/networks'
    schedule:
      interval: 'weekly'
    groups:
      core-dependencies:
        patterns:
          - '*'
