$schema = "https://railway.com/railway.schema.json"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["yarn"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["yarn install --frozen-lockfile && yarn packages:build && cd backend"]
