name: Main Branch

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Run the tests'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        folders: ['smart-contracts', 'backend']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: yarn
        shell: bash

      - run: 'yarn build'
        shell: bash

      - name: 'run lint'
        run: yarn workspace @relay-protocol/${{matrix.folders}} lint
        shell: bash

      - name: 'run tests'
        run: yarn workspace @relay-protocol/${{matrix.folders}} run test
        shell: bash

  build-docker-image:
    name: 'Build/push Docker image'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: github.repository == 'reservoirprotocol/vaults'
    permissions:
      contents: read
      packages: write
    needs:
      - run-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/reservoirprotocol/vaults:latest
            ghcr.io/reservoirprotocol/vaults:${{ github.sha }}
            ghcr.io/reservoirprotocol/vaults:${{ github.ref_name }}-${{ github.sha }}
          build-args: |
            TAG=${{ github.ref_name }}

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    if: github.repository == 'reservoirprotocol/vaults' && github.ref == 'refs/heads/main'
    needs: [build-docker-image]
    environment: dev
    steps:
      - name: pull docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/unevenlabs/infrastructure/deployer:latest
        shell: bash

      - name: deploy to dev
        run: |
          docker run -it ghcr.io/unevenlabs/infrastructure/deployer:latest -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e GITHUB_SHA=${{ github.sha }} -e ENVIRONMENT=dev vaults
        shell: bash
